# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'MockUserDefaultsDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MockUserDefaultsDemo
  pod 'R.swift', '~> 5.0'

  target 'MockUserDefaultsDemoTests' do
    inherit! :search_paths
    pod 'MockUserDefaults', :path => '../'
  end

end
