name: MockUserDefaultsDemo
attributes:
  ORGANIZATIONNAME: 417.72KI
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 11.0
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: false
    CLANG_ENABLE_OBJC_ARC: true
options:
  xcodeVersion: 10.2
  bundleIdPrefix: io.github.417-72KI
targets:
  MockUserDefaultsDemo:
    type: application
    platform: iOS
    deploymentTarget: 11.0
    sources: 
      - MockUserDefaultsDemo
      - path: Libs/R_swift/R.generated.swift
        optional: true
        createIntermediateGroups: true
    info:
      path: MockUserDefaultsDemo/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: '6.0'
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        # CFBundleShortVersionString: 1.0.0
        # CFBundleVersion: 1
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UIRequiredDeviceCapabilities: 
          - armv7
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
        PRODUCT_NAME: MockUserDefaultsDemo
        PRODUCT_BUNDLE_IDENTIFIER: io.github.417-72KI.MockUserDefaultsDemo
        CODE_SIGN_STYLE: Manual
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        LIBRARY_SEARCH_PATHS: $(inherited)
      configs:
        debug: 
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: ""
        release: 
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: ""
          EXCLUDED_SOURCE_FILE_NAMES: Mock*
    dependencies:
      - framework: "Carthage/Build/RxSwift.xcframework"
        codeSign: false
      - framework: "Carthage/Build/RxRelay.xcframework"
        codeSign: false
      - framework: "Carthage/Build/RxCocoa.xcframework"
        codeSign: false
      - framework: "Carthage/Build/RxDataSources.xcframework"
        codeSign: false
      - framework: "Carthage/Build/Differentiator.xcframework"
        codeSign: false
    preBuildScripts:
      - name: Lint
        script: |
                if which swiftlint >/dev/null; then
                swiftlint
                else
                echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
      - name: R.swift
        script: ${PODS_ROOT}/R.swift/rswift generate ${SRCROOT}/Libs/R_swift/R.generated.swift
        inputFiles:
          - $(TEMP_DIR)/rswift-lastrun
        outputFiles:
          - $(SRCROOT)/Libs/R_swift/R.generated.swift
  MockUserDefaultsDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - path: MockUserDefaultsDemoTests
        excludes: [Info.plist] # Workaround: https://github.com/yonaskolb/XcodeGen/issues/1058#issuecomment-820501341
    info:
      path: MockUserDefaultsDemoTests/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: BNDL
        # CFBundleShortVersionString: 1.0.0
        # CFBundleVersion: 1
    settings:
      INFOPLIST_FILE: MockUserDefaultsDemoTests/info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/MockUserDefaultsDemo.app/MockUserDefaultsDemo
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: iPhone Developer
      DEVELOPMENT_TEAM: ""
    dependencies:
      - target: MockUserDefaultsDemo
      - framework: "Carthage/Build/Quick.xcframework/ios-arm64_i386_x86_64-simulator/Quick.framework"
        codeSign: false
      - framework: "Carthage/Build/Nimble.xcframework/ios-arm64_i386_x86_64-simulator/Nimble.framework"
        codeSign: false
      - framework: "Carthage/Build/RxTest.xcframework/ios-arm64_i386_x86_64-simulator/RxTest.framework"
        codeSign: false
      - framework: "Carthage/Build/RxBlocking.xcframework/ios-arm64_i386_x86_64-simulator/RxBlocking.framework"
        codeSign: false
