
default_platform(:ios)

platform :ios do
  desc "Runs unit tests for DemoApp"
  lane :test_demo do
    scan(
      workspace: 'DemoApp/MockUserDefaultsDemo.xcworkspace',
      scheme: 'MockUserDefaultsDemo',
      skip_package_dependencies_resolution: true,
      clean: true
    )
  end
end
