
default_platform(:ios)

platform :ios do
  desc "Runs all unit tests"
  lane :test do
    scan(
      scheme: 'MockUserDefaults',
      clean: true
    )
  end

  desc "Runs unit tests for DemoApp"
  lane :test_demo do
    scan(
      workspace: 'DemoApp/MockUserDefaultsDemo.xcworkspace',
      scheme: 'MockUserDefaultsDemo',
      clean: true
    )
  end
end
