name: MockUserDefaultsDemo
attributes:
  ORGANIZATIONNAME: 417.72KI
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: false
    CLANG_ENABLE_OBJC_ARC: true
options:
  xcodeVersion: 13.2
  bundleIdPrefix: io.github.417-72KI
packages:
  MockUserDefaultsDemoLib:
    path: '../MockUserDefaultsDemoLib'
targets:
  MockUserDefaultsDemo:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources: 
      - MockUserDefaultsDemo
    info:
      path: MockUserDefaultsDemo/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: '6.0'
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        # CFBundleShortVersionString: 1.0.0
        # CFBundleVersion: 1
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        # UIMainStoryboardFile: Main
        UIRequiredDeviceCapabilities: 
          - armv7
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
        PRODUCT_NAME: MockUserDefaultsDemo
        PRODUCT_BUNDLE_IDENTIFIER: io.github.417-72KI.MockUserDefaultsDemo
        CODE_SIGN_STYLE: Manual
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        LIBRARY_SEARCH_PATHS: $(inherited)
        VALID_ARCHS: arm64 arm64e
      configs:
        debug: 
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: ""
          VALID_ARCHS[sdk=iphonesimulator*]: x86_64 arm64
        release: 
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: ""
          EXCLUDED_SOURCE_FILE_NAMES: Mock*
    preBuildScripts:
      - name: Lint
        script: |
                if which swiftlint >/dev/null; then
                  cd .. && swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
    dependencies:
      - package: MockUserDefaultsDemoLib
