name: Renovate
on:
  pull_request:
    paths:
      - '.github/renovate.json'
      - '.github/workflows/renovate.yml'
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - id: validate
        run: renovate-config-validator > validation-result.txt
      - uses: actions/github-script@v6
        if: ${{ always() }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const ids = comments.data
              .filter(e => e.user.id == 41898282)
              .map(e => e.id)
            await Promise.all(ids.map(async (id) => {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: id,
              })
            }))

            const fs = require("fs").promises
            const result = await fs.readFile('validation-result.txt', 'utf8')
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "## Renovate config validation result\n```\n" + result.trimEnd() + "\n```"
            })
