name: Renovate
on:
  pull_request:
    paths:
      - 'renovate.json'
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          yarn global add renovate
          renovate-config-validator
